[project]
name = "perf-aware"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.setuptools.packages.find]
where = ["python_implementation/src"]

[tool.setuptools.package-dir]
"" = "python_implementation/src"
