// haven't used this yet. Feels like it belongs instead of always using an enum array
const DecodedInstr = struct {
    d: ?u1,
    w: ?u1,
    s: ?u1,
    v: ?u1,
    z: ?u1,
    mod: ?u2,
    reg: ?u3,
    rm: ?u3,
    sr: ?u2,
    esc_opcode_hi: ?u3,
    esc_opcode_lo: ?u3,
    disp_lo: ?u8,
    disp_hi: ?u8,
    data: ?u8,
    data_if_w_eq_1: ?u8,
    data_if_sw_eq_01: ?u8,
    data_8: ?u8,
    data_lo: ?u8,
    data_hi: ?u8,
    addr_lo: ?u8,
    addr_hi: ?u8,
    ip_lo: ?u8,
    ip_hi: ?u8,
    ip_inc_lo: ?u8,
    ip_inc_hi: ?u8,
    ip_inc8: ?u8,
    cs_lo: ?u8,
    cs_hi: ?u8,
};
